# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chimps}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philip (flip) Kromer"]
  s.date = %q{2010-05-20}
  s.default_executable = %q{chimps}
  s.description = %q{Find data on any subject! A command-line interface to the Infochimps data repository}
  s.email = %q{flip@infochimps.org}
  s.executables = ["chimps"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "bin/chimps",
     "examples/batch.yaml",
     "lib/chimps.rb",
     "lib/chimps/cli.rb",
     "lib/chimps/commands.rb",
     "lib/chimps/commands/base.rb",
     "lib/chimps/commands/batch.rb",
     "lib/chimps/commands/create.rb",
     "lib/chimps/commands/destroy.rb",
     "lib/chimps/commands/download.rb",
     "lib/chimps/commands/help.rb",
     "lib/chimps/commands/list.rb",
     "lib/chimps/commands/query.rb",
     "lib/chimps/commands/search.rb",
     "lib/chimps/commands/show.rb",
     "lib/chimps/commands/test.rb",
     "lib/chimps/commands/update.rb",
     "lib/chimps/commands/upload.rb",
     "lib/chimps/config.rb",
     "lib/chimps/request.rb",
     "lib/chimps/response.rb",
     "lib/chimps/typewriter.rb",
     "lib/chimps/utils.rb",
     "lib/chimps/utils/error.rb",
     "lib/chimps/utils/extensions.rb",
     "lib/chimps/utils/uses_curl.rb",
     "lib/chimps/utils/uses_model.rb",
     "lib/chimps/utils/uses_yaml_data.rb",
     "lib/chimps/workflows.rb",
     "lib/chimps/workflows/batch.rb",
     "lib/chimps/workflows/downloader.rb",
     "lib/chimps/workflows/uploader.rb",
     "spec/chimps/cli_spec.rb",
     "spec/chimps/commands/base_spec.rb",
     "spec/chimps/commands/list_spec.rb",
     "spec/chimps/response_spec.rb",
     "spec/chimps/typewriter_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/custom_matchers.rb"
  ]
  s.homepage = %q{http://github.com/infochimps/chimps}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Search, browse, download and create datasets on the infochimps.org data repository, and query the api.}
  s.test_files = [
    "spec/chimps/cli_spec.rb",
     "spec/chimps/commands/base_spec.rb",
     "spec/chimps/commands/list_spec.rb",
     "spec/chimps/response_spec.rb",
     "spec/chimps/typewriter_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/custom_matchers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

